### ISSUE TITLE
OptimizeWarpPoints = true breaks pathfinding

### ISSUE THREAD

**Issue by Yagisan** [ameisen/SV-SpriteMaster#13]
This was an interesting bug to track down, and is present in both 0.14.0 and 0.15.0-alpha.1

After a certain number of new locations are added, when `OptimizeWarpPoints = true`, pathfinding is broken on the [Juliet & Jessie](https://www.nexusmods.com/stardewvalley/mods/6398) ClearingHouse map.

[Please see this video](https://youtu.be/F0UT5utYOJ0) 1:31 to see the behaviour with  `OptimizeWarpPoints = true`

When  `OptimizeWarpPoints = false` pathfinding works correctly.

[Please see this video](https://youtu.be/lLH-lVia7wk) 1:26 to see the behaviour with  `OptimizeWarpPoints = false`

This issue has been difficult to track down, as without a certain number of mods, it behaves like `OptimizeWarpPoints = false`.

[I have prepared the minimum number of mods that I needed to reproduce this bug here](https://www.dropbox.com/s/nay7ypi44c6s6ye/OptimizeWarpPoints_minium_viable_modlist.7z?dl=0) 140MB

I am happy to test any debugging builds of SpriteMaster to help track down this issue.

**Comment by Yagisan** [comment]
I have replicated this in 0.15.0-Alpha.2

**Comment by ameisen** [comment]
Relevant timestamps in videos:

https://youtu.be/F0UT5utYOJ0?t=66

https://youtu.be/lLH-lVia7wk?t=68

**Comment by ameisen** [comment]
This was due to the pathfinding code using a stable priority queue, and pre-loading it with all locations (with their distance set to `int.MaxValue` as a sentinel).

This resulted in updating their positions in the queue _not_ honoring warp/door order within a location - that is, if a location had [A, B] in their warps, but the original order in the queue was [B, A], they would retain the [B, A] order in the queue if their priority were the same. This resulted in a divergence in behavior from vanilla code.

This is fixed in 51836e1b344258b665b82f004d34a5d2aecb133e.

**Comment by ameisen** [comment]
This was due to the pathfinding code using a stable priority queue, and pre-loading it with all locations (with their distance set to `int.MaxValue` as a sentinel).

This resulted in updating their positions in the queue _not_ honoring warp/door order within a location - that is, if a location had [A, B] in their warps, but the original order in the queue was [B, A], they would retain the [B, A] order in the queue if their priority were the same. This resulted in a divergence in behavior from vanilla code.

This is fixed in 51836e1b344258b665b82f004d34a5d2aecb133e.

**Comment by Yagisan** [comment]
Thank you. I've confirmed this is fixed.
